[concentration]
	#Whether the window size and pos is customized
	customized = false
	#Whether the window pos should related to the monitor
	related = false
	#X coordinate
	#Range: > -2147483648
	x = 0
	#Y coordinate
	#Range: > -2147483648
	y = 0
	#Width
	#Range: > 1
	width = 800
	#Height
	#Range: > 1
	height = 600
	#Fullscreen mode
	#Allowed Values: BORDERLESS, NATIVE
	fullscreen = "BORDERLESS"
