[metadata]
	#The URL to download track metadata from. This should generally be left at the default.
	url = "https://raw.githubusercontent.com/GlyphMods/wailt/1.20.6/src/main/resources/tracks.json"
	#Force the mod to use track metadata embedded in the JAR. Only useful for development.
	force-embedded = false

[toast]
	#How long to show the toast on screen, in seconds
	duration = 5.0
	#Always use white text for the artist name in the toast
	disable-color = false
	#Automatically show the toast when the music changes
	automatically-show = true
