services:
  mc:
    container_name: boundless-mc
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    restart: always
    ports:
      - "25565:25565"
      - "24454:24454/udp"
    environment:
      EULA: "TRUE"
      MEMORY: "4g"
      MOD_PLATFORM: MODRINTH
      MODRINTH_MODPACK: ScTwzzH2
      MODRINTH_DEFAULT_VERSION_TYPE: beta
      MODRINTH_EXCLUDE_FILES: |
        sound
        sodium-extra
        watermedia
        world-host
      MODRINTH_OVERRIDES_EXCLUSIONS: |
        resourcepacks/*
        shaderpacks/*
      SERVER_NAME: "A Boundless Horizons Modpack Server"
      MOTD: "\u00a72A\u00a76 Boundless \u00a71Horizons \u00a72Modpack Server"
      ICON: "https://raw.githubusercontent.com/vaporvee/BoundlessHorizons/refs/heads/main/assets/icon.png"
      DIFFICULTY: "NORMAL"
      SPAWN_PROTECTION: "0"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - ./data:/data